import { ConfigProvider } from "antd"
import { StoreProvider } from "@/store";
import { AuthProvider } from "@/providers/AuthProvider";
import "@/css/globals.css";
import type { Metadata, Viewport } from "next";


export const metadata: Metadata = {
  title: "Ai Agent",
  description: "Generated by create next app",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black",
  }
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
}




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider
          theme={{
            components: {
              Select: {
                selectorBg: "#181A1D",
              },
            },
          }}
        >
          <AuthProvider>
            <StoreProvider>
              {children}
            </StoreProvider>
          </AuthProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
